cmake_minimum_required(VERSION 3.20.0)

set(VAR_VARIABLE Variable)
set(VAR_TRUE TRUE)
set(VAR_FALSE FALSE)

message("VAR_VARIABLE: ")
if (VAR_VARIABLE)
  message(TRUE)
else()
  message(FALSE)
endif()

message("VAR_TRUE: ")
if (VAR_TRUE)
  message(TRUE)
else()
  message(FALSE)
endif()

message("VAR_FALSE: ")
if (VAR_FALSE)
  message(TRUE)
else()
  message(FALSE)
endif()

message("not empty string: ")
if ("not empty string")
  message(TRUE)
else()
  message(FALSE)
endif()

message("TRUE: ")
if ("TRUE")
  message(TRUE)
else()
  message(FALSE)
endif()

message("FALSE: ")
if ("FALSE")
  message(TRUE)
else()
  message(FALSE)
endif()

set(VAR_VARIABLE2 Variable-NOTFOUND)
message("VAR_VARIABLE2: ")
if (VAR_VARAIBLE2)
  message(TRUE)
else()
  message(FALSE)
endif()

# 判断是否定义变量
set(VAR_NAME myname)
set(VAR_CACHE "cahe variable" CACHE STRING "定义缓存变量")
set(ENV{CXX} "clang++")
if (DEFINED VAR_NAME)
  message("定义了 VAR_NAME")
endif()
if (DEFINED CACHE{VAR_CACHE})
  message("定义了 VAR_CACHE")
endif()
if (DEFINED ENV{CXX})
  message("定义了 CXX")
endif()